src/Entity/Maintenance.php
<?php

namespace App\Entity;

use App\Repository\MaintenanceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaintenanceRepository::class)]
class Maintenance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $serviceDate = null;

    #[ORM\Column(nullable: true)]
    private ?bool $oilChange = null;

    #[ORM\Column(nullable: true)]
    //inspection des freins
    private ?bool $brakeInspection = null;

    #[ORM\Column(nullable: true)]
    //Changement de pneu
    private ?bool $tireChange = null;

    #[ORM\Column(nullable: true)]
    private ?bool $filterChange = null;

    #[ORM\Column(nullable: true)]
    //Climatisation
    private ?bool $fluidTopUp = null;

    #[ORM\ManyToOne(inversedBy: 'maintenances')]
    private ?Car $Car = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getServiceDate(): ?\DateTimeInterface
    {
        return $this->serviceDate;
    }

    public function setServiceDate(?\DateTimeInterface $serviceDate): static
    {
        $this->serviceDate = $serviceDate;

        return $this;
    }

    public function isOilChange(): ?bool
    {
        return $this->oilChange;
    }

    public function setOilChange(?bool $oilChange): static
    {
        $this->oilChange = $oilChange;

        return $this;
    }

    public function isBrakeInspection(): ?bool
    {
        return $this->brakeInspection;
    }

    public function setBrakeInspection(?bool $brakeInspection): static
    {
        $this->brakeInspection = $brakeInspection;

        return $this;
    }

    public function isTireChange(): ?bool
    {
        return $this->tireChange;
    }

    public function setTireChange(?bool $tireChange): static
    {
        $this->tireChange = $tireChange;

        return $this;
    }

    public function isFilterChange(): ?bool
    {
        return $this->filterChange;
    }

    public function setFilterChange(?bool $filterChange): static
    {
        $this->filterChange = $filterChange;

        return $this;
    }

    public function isFluidTopUp(): ?bool
    {
        return $this->fluidTopUp;
    }

    public function setFluidTopUp(?bool $fluidTopUp): static
    {
        $this->fluidTopUp = $fluidTopUp;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->Car;
    }

    public function setCar(?Car $Car): static
    {
        $this->Car = $Car;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }
}

templates/Maintenance/CreateMaintenance.html.twig
{% extends 'base_admin.html.twig' %}

{% block pageTitle %}Add Maintenance{% endblock %}

{% block pageBody %}
    <div class="row">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Add Maintenance Record</h4>
                    <form method="post">
                        {{ form_start(form) }}
                        <div class="row g-3">
                            <div class="col-md-6">
                                {% for message in app.flashes('success') %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.serviceDate, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                {{ form_label(form.email, 'Email', {'label_attr': {'class': 'form-check-label'}}) }}
                                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form_widget(form.oilChange, {'attr': {'class': 'form-check-input'}}) }}
                                    {{ form_label(form.oilChange, 'Oil Change', {'label_attr': {'class': 'form-check-label'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form_widget(form.brakeInspection, {'attr': {'class': 'form-check-input'}}) }}
                                    {{ form_label(form.brakeInspection, 'Brake Inspection', {'label_attr': {'class': 'form-check-label'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form_widget(form.tireChange, {'attr': {'class': 'form-check-input'}}) }}
                                    {{ form_label(form.tireChange, 'Tire Change', {'label_attr': {'class': 'form-check-label'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form_widget(form.filterChange, {'attr': {'class': 'form-check-input'}}) }}
                                    {{ form_label(form.filterChange, 'Filter Change', {'label_attr': {'class': 'form-check-label'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form_widget(form.fluidTopUp, {'attr': {'class': 'form-check-input'}}) }}
                                    {{ form_label(form.fluidTopUp, 'Fluid Top-Up', {'label_attr': {'class': 'form-check-label'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.car, 'Choice you car', {'label_attr': {'class': 'form-check-label'}}) }}
                                    {{ form_widget(form.car, {'attr': {'class': 'form-check-select'}}) }}
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Save Maintenance</button>
                        {{ form_end(form) }}
                    </form>
                </div>
            </div>
    </div>

{% endblock %}

{% block additionalJavascript %}
{% endblock %}

templates/Maintenance/list.html.twig
{% extends 'base_admin.html.twig' %}

{% block pageTitle %}List Car{% endblock %}


{% block pageBody %}
    <div class="row">

        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Car List saved</h4>
            <p class="card-description"> Add class <code>.table</code>
            </p>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Year</th>
                    <th>Mile Age</th>
                  </tr>
                </thead>
                <tbody>
                {% for car in cars %}
                  <tr>
                    <td>{{ car.make }}</td>
                    <td>{{ car.model }}</td>
                    <td>1{{ car.year }}</td>
                    <td><label class="badge badge-danger">{{ car.mileAge }} km</label></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

{% block additionalJavascript %}

{% endblock %}

templates/Maintenance/new.html.twig
{% extends 'base_admin.html.twig' %}

{% block pageTitle %}Add Car{% endblock %}


{% block pageBody %}
<div class="container mt-12">
    <h3 class="mb-4">Register Car</h3>
    <form id="carRegistrationForm">
        <div class="row g-3">
            <div class="row">
                <div class="form-group">
                    <label for="SelectMakeChoice" class="form-label">Make</label>
                    <select id="btnSelectMake" class="form-control" required>
                        <option value="">Select a Car Make</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label for="SelectModelChoice" class="form-label">Model</label>
                    <select id="btnSelectModel" class="form-control" required>
                        <option value="">Select a Car Model</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label for="SelectYearChoice" class="form-label">Year</label>
                    <select id="btnSelectYear" class="form-control" required>
                        <option value="">Select a Car Year</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group-sm">
                    <label for="mileage" class="form-label">Mileage</label>
                    <div class="input-group">
                        <input type="number" id="mileage" name="mileage" class="form-control" placeholder="Enter mileage" required>
                        <span class="input-group-text">km</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content mt-5">
            <button type="submit" class="btn btn-primary">Register Car</button>
        </div>
    </form>
    </div>
{% endblock %}

{% block additionalJavascript %}
    <script src="{{ asset('js/script.js') }}"> </script>
{% endblock %}